/*Does Weight_status impact cholestrol*/

DATA WORK.HEART;
	SET SASHELP.HEART;
	IF UPCASE(WEIGHT_STATUS) NE "UNDERWEIGHT";
RUN;

TITLE "PROC TTEST = Chrolesterol vs Weight Status";
PROC TTEST DATA=WORK.HEART;
	CLASS WEIGHT_STATUS;
	VAR CHOLESTEROL;
RUN;

/* Reject the Null Hypothesis*/

ODS GRAPHICS ON;

TITLE "One way anova age of death vs chol status";
PROC GLM DATA=SASHELP.HEART PLOTS=DIAGNOSTICS(UNPACK);
	CLASS CHOL_STATUS;
	MODEL AGEATDEATH=CHOL_STATUS;
	MEANS CHOL_STATUS / HOVTEST;
RUN;
QUIT;
ODS GRAPHICS OFF;

/* ACCEPT the Null Hypothesis: (VARIANCES ATE EQUAL)*/
/*R-SQUR LESS : NOT CORRELATED*/

ODS GRAPHICS ON;

TITLE "Post Hoc Pairwise Comparision";
PROC ANOVA DATA=SASHELP.HEART;
	CLASS CHOL_STATUS;
	MODEL AGEATDEATH=CHOL_STATUS;
	LSMEANS CHOL_STATUS / PDIFF=ALL ADJUST=TUKEY;
	LSMEANS CHOL_STATUS / PDIFF=CONTROL("Borderline") ADJUST=DUNNETT;
RUN;
QUIT;
ODS GRAPHICS OFF;

PROC ANOVA DATA=SASHELP.HEART;
	CLASS CHOL_STATUS;
	MODEL AGEATDEATH=CHOL_STATUS;
	MEANS CHOL_STATUS/ tukey lines;
RUN;
